[project]
name = "preeminence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "joblib>=1.5.3",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "streamlit>=1.53.0",
]
